### ISSUE TITLE
Can't work on windows.

### ISSUE THREAD

**Issue by xi-loong** [benley/python-glog#10]
This my test code:
```
import colored_glog as glog
glog.warning("test")
```
and the output is:
```
W1029 12:23:24.313652 2984 <stdin>:1] [33mtest[0m
```

**Comment by benley** [comment]
colored-glog is a fork of this project, and the part you're having trouble with is not here.  Please open an issue over in the forked repo: https://github.com/xiaoxq/colored-glog
