### ISSUE TITLE
ImportError: No module named glog

### ISSUE THREAD

**Issue by yunyunhello** [benley/python-glog#8]
I follow the following link to install python-glog in anaconda
https://anaconda.org/anaconda/glog
using command
$conda install -c anaconda glog 

However, when I execute
"import glog as log"
it prompts the following error:
     import glog as log
ImportError: No module named glog

What should I do?
Thanks a lot !

**Comment by yunyunhello** [comment]
I changed the installation method and solved successfully.

I downloaded the "glog-0.3.1-py2.py3-none-any.whl" from the official download website(https://pypi.org/project/glog/0.3.1/#files)
Then "pip install glog-0.3.1-py2.py3-none-any.whl"
import glog successfully.

**Comment by FishermanZzhang** [comment]
how solve it by conda ？
