### ISSUE TITLE
How to write glog output to file?

### ISSUE THREAD

**Issue by gregchu** [benley/python-glog#9]
Can glog by default write its output to a log file? or do we need to manually pipe the stdout to file (with something like 2>&1 | tee log.INFO)

**Comment by benley** [comment]
This implementation of glog doesn't do any logging to files on its own. For that functionality, you might consider `absl.logging`, which appears to be a more direct port of google's internal pyglib.logging module: https://github.com/abseil/abseil-py/blob/master/absl/logging/__init__.py
